ODOICHON/server

- build.gradle.kts
- src/main/kotlin/com/example/jhouse_server/global/JasyptConfig.kt
- src/main/resources/application.yml
[코틀린+스프링환경에서 Jasypt를 이용한 yml 암호화하기](https://codemasterkimc.tistory.com/569) 참고하여 진행했습니다.
> [chore/project-setting] #1 Jasypt 암호화 설정 추가

- build.gradle.kts
- src/main/kotlin/com/example/jhouse_server/admin/user/controller/AdminUserController.kt
- src/main/resources/templates/login.html
> feat: admin nginx test

- scripts/switch.sh
nginx 포워딩 설정 (switch.sh 스크립트 수정)
> feat: nginx admin deploy

- build.gradle.kts
- src/main/kotlin/com/example/jhouse_server/admin/user/controller/AdminUserController.kt
- src/main/kotlin/com/example/jhouse_server/global/config/WebConfig.kt
버전 문제로 view resolver 작동안함 -> starter 버전으로 수정
> fix: thymeleaf version issue

- src/main/kotlin/com/example/jhouse_server/domain/user/controller/UserController.kt
- src/main/kotlin/com/example/jhouse_server/domain/user/service/UserService.kt
- src/main/kotlin/com/example/jhouse_server/domain/user/service/UserServiceImpl.kt
- src/main/kotlin/com/example/jhouse_server/global/util/RedisUtil.kt
- src/test/kotlin/com/example/jhouse_server/domain/user/controller/UserControllerTest.kt
> refactor: reissue api 수정

- src/main/kotlin/com/example/jhouse_server/domain/user/controller/UserController.kt
- src/main/kotlin/com/example/jhouse_server/domain/user/service/UserServiceImpl.kt
- src/main/kotlin/com/example/jhouse_server/global/jwt/TokenProvider.kt
- src/main/kotlin/com/example/jhouse_server/global/util/RedisUtil.kt
- JWT 만료시간 재수정
- 전화번호 인증코드 redis 만료시간 설정
> refactor: redis 만료시간 설정

- src/main/kotlin/com/example/jhouse_server/admin/anaylsis/controller/AdminAnalysisController.kt
- src/main/resources/templates/analysis/age.html
- linux 환경에서 path pattern이 달라서, view resolver 가 template을 찾지 못함 
- cdn 방식의 script 태그에서 cors 에러 발견
> fix: path pattern 변경 & cors 에러

- .github/workflows/CI.yml
- src/main/kotlin/com/example/jhouse_server/domain/user/repository/UserRepositoryImpl.kt
- src/main/resources/templates/analysis/age.html
- 특정 연령대의 사용자가 존재하지 않을 시(0%) 처리 로직 변경
> fix: admin age analysis

- .github/workflows/CI.yml
- build.gradle.kts
- src/main/kotlin/com/example/jhouse_server/admin/board/controller/AdminBoardController.kt
- src/main/kotlin/com/example/jhouse_server/admin/board/dto/AdminBoardListResponse.kt
- src/main/kotlin/com/example/jhouse_server/admin/board/dto/AdminBoardSearch.kt
- src/main/kotlin/com/example/jhouse_server/admin/board/dto/FilterList.kt
- src/main/kotlin/com/example/jhouse_server/admin/board/service/AdminBoardService.kt
- src/main/kotlin/com/example/jhouse_server/domain/board/repository/BoardRepository.kt
- src/main/kotlin/com/example/jhouse_server/domain/board/repository/BoardRepositoryCustom.kt
- src/main/kotlin/com/example/jhouse_server/domain/board/repository/BoardRepositoryImpl.kt
- src/main/kotlin/com/example/jhouse_server/domain/board/repository/dto/AdminBoardResult.kt
- src/main/resources/templates/board/fix.html
- src/main/resources/templates/fragments/nav.html
- 게시물 검색 -> 동적 쿼리 작성
- 페이지네이션 -> 5 페이지 단위 (이전&다음 버튼 포함)
- Thymeleaf 뷰 작업
- 반응형 적용 x
> feat: admin boardlist query & view

- src/main/kotlin/com/example/jhouse_server/domain/user/controller/UserController.kt
- src/main/kotlin/com/example/jhouse_server/global/jwt/TokenProvider.kt
> refactor: token 만료시간 수정

- src/main/kotlin/com/example/jhouse_server/domain/user/controller/UserController.kt
> refactor: cookie default값 추가

- src/main/kotlin/com/example/jhouse_server/domain/user/controller/UserController.kt
- src/main/kotlin/com/example/jhouse_server/global/jwt/TokenProvider.kt
> refactor: 토큰 만료시간 수정

- .github/workflows/health-check-user.yml
> 3일마다 0시0분에 서버 인스턴스 헬스체크
- 변경 내용 : cron 주기를 3일마다 로 변경
이유 : 테스트 후 적용
> fix: cron change

- src/main/kotlin/com/example/jhouse_server/domain/board/dto/BoardReqDto.kt
- src/main/kotlin/com/example/jhouse_server/domain/comment/dto/CommentResDto.kt
- src/main/resources/static/docs/board.html
- src/main/resources/static/docs/comment.html
> 한 줄로 정리해주세요.
createdAt의 타입 String에서 LocalDate로 타입 변경
- createdAt의 타입 String에서 LocalDate로 타입 변경
이유 : 프론트엔드 측에서 포멧팅을 직접 처리하기로 했습니다.
> [hotfix/board-service]createdAt의 타입 String에서 LocalDate로 타입 변경

- src/main/kotlin/com/example/jhouse_server/domain/board/dto/BoardReqDto.kt
- src/main/kotlin/com/example/jhouse_server/domain/comment/dto/CommentResDto.kt
- src/main/resources/static/docs/board.html
- src/main/resources/static/docs/comment.html
> [hotfix/board-service] Date 타입으로 재변경

- README.md
> docs: 회고 문서화 업데이트

- src/docs/asciidoc/board.adoc
- src/main/kotlin/com/example/jhouse_server/domain/board/controller/BoardController.kt
- src/main/kotlin/com/example/jhouse_server/domain/board/repository/BoardRepositoryCustom.kt
- src/main/kotlin/com/example/jhouse_server/domain/board/repository/BoardRepositoryImpl.kt
- src/main/kotlin/com/example/jhouse_server/domain/board/service/BoardService.kt
- src/main/kotlin/com/example/jhouse_server/domain/board/service/BoardServiceImpl.kt
- src/main/resources/static/docs/board.html
- src/test/kotlin/com/example/jhouse_server/domain/board/controller/BoardControllerTest.kt
> 한 줄로 정리해주세요.
말머리에 따른 게시글 검색
- 게시판에 따른 게시글 검색 함수명 변경
이유 : 함수명 명명규칙 통일화를 위해 함수명 변경하였습니다.
> [feature/board-service] 말머리에 따른 게시글 검색

- src/main/resources/static/docs/board.html
> 한 줄로 정리해주세요.
말머리에 따른 게시글 전체 조회 기능 테스트 코드 작성 및 문서화 누락 파일 재업로드
- 없습니다.
> [feature/board-service] 게시글 전체 조회 기능 문서화

- src/main/kotlin/com/example/jhouse_server/domain/board/repository/BoardRepositoryImpl.kt
> 한 줄로 정리해주세요.
게시글 조회 시, useYn 필터링 추가
- 게시글 조회 시, useYn 필터링 추가
이유 : soft delete 된 게시글까지 노출되고 있어서 조건을 추가했습니다.
> [hotfix/board-service] 게시글 조회 시, useYn 필터링 추가

- src/main/kotlin/com/example/jhouse_server/domain/board/repository/BoardRepositoryImpl.kt
- src/main/resources/static/docs/board.html
> main <- develop

- .github/workflows/CD.yml
- src/main/resources/application-prod.yml
- src/main/resources/application.yml
> feat: cloud watch

- src/main/kotlin/com/example/jhouse_server/global/aop/log/trace/LogTrace.kt
> fix: threadlocal

- README.md
- build.gradle.kts
- src/main/kotlin/com/example/jhouse_server/domain/board/controller/BoardController.kt
- src/main/kotlin/com/example/jhouse_server/domain/board/dto/BoardReqDto.kt
> image가 하나도 없는 게시물에 한해서 리스트 조회시, 썸네일url을 null로 처리
> Fix: imageUrls index error

- docker-compose.yml
- src/docs/asciidoc/board.adoc
- src/main/kotlin/com/example/jhouse_server/domain/board/controller/BoardController.kt
- src/main/kotlin/com/example/jhouse_server/domain/board/dto/BoardReqDto.kt
- src/main/kotlin/com/example/jhouse_server/domain/board/repository/BoardRepositoryCustom.kt
- src/main/kotlin/com/example/jhouse_server/domain/board/repository/BoardRepositoryImpl.kt
- src/main/kotlin/com/example/jhouse_server/domain/board/service/BoardService.kt
- src/main/kotlin/com/example/jhouse_server/domain/board/service/BoardServiceImpl.kt
- src/main/resources/static/docs/board.html
- src/test/kotlin/com/example/jhouse_server/domain/board/controller/BoardControllerTest.kt
- src/test/kotlin/com/example/jhouse_server/domain/board/service/BoardServiceImplTest.kt
> (prefix category, category, 검색) 3개의 api에 대해서 api 통일화
> fix: getBoardAll querydsl

- src/main/kotlin/com/example/jhouse_server/domain/record/service/RecordServiceImpl.kt
- src/test/kotlin/com/example/jhouse_server/domain/record/service/RecordServiceImplTest.kt
> record 단일 조회 반환 값 수정
- 변경 내용
이유 :
> refactor: 반환값 수정

- src/main/kotlin/com/example/jhouse_server/domain/board/service/BoardServiceImpl.kt
> Fix: 게시물 생성 시, 캐시 삭제

- src/main/kotlin/com/example/jhouse_server/domain/record/dto/RecordDto.kt
- src/main/kotlin/com/example/jhouse_server/domain/record/repository/RecordRepositoryCustom.kt
- src/main/kotlin/com/example/jhouse_server/domain/record/repository/RecordRepositoryImpl.kt
- src/main/kotlin/com/example/jhouse_server/domain/record/service/RecordServiceImpl.kt
> [refactor]back-office

- src/main/kotlin/com/example/jhouse_server/domain/house/dto/HouseReqDto.kt
- src/main/resources/static/docs/board.html
- src/main/resources/static/docs/comment.html
- src/main/resources/static/docs/house.html
- src/main/resources/static/docs/love.html
- src/main/resources/static/docs/record.html
- src/main/resources/static/docs/record_category.html
- src/main/resources/static/docs/record_comment.html
- src/main/resources/static/docs/record_review.html
- src/main/resources/static/docs/user.html
- src/test/kotlin/com/example/jhouse_server/domain/house/controller/HouseControllerTest.kt
> 한 줄로 정리해주세요.
빈집 게시글 상세 조회 시 응답데이터 수정
-  빈집 게시글 상세 조회 시 응답데이터 수정
이유 :  게시글 데이터 누락 ( 매물 크기 )
> [Feat/house service] 빈집 게시글 상세 조회 시 응답데이터 수정

- src/main/kotlin/com/example/jhouse_server/domain/house/dto/HouseReqDto.kt
- src/main/resources/static/docs/board.html
- src/main/resources/static/docs/comment.html
- src/main/resources/static/docs/house.html
- src/main/resources/static/docs/love.html
- src/main/resources/static/docs/record.html
- src/main/resources/static/docs/record_category.html
- src/main/resources/static/docs/record_comment.html
- src/main/resources/static/docs/record_review.html
- src/main/resources/static/docs/user.html
> [fix/house service] 응답 DTO 내 변수 매핑 순서 오류 해결

- src/main/kotlin/com/example/jhouse_server/domain/house/dto/HouseReqDto.kt
- src/main/resources/static/docs/board.html
- src/main/resources/static/docs/comment.html
- src/main/resources/static/docs/error.html
- src/main/resources/static/docs/house.html
- src/main/resources/static/docs/love.html
- src/main/resources/static/docs/record.html
- src/main/resources/static/docs/record_category.html
- src/main/resources/static/docs/record_comment.html
- src/main/resources/static/docs/record_review.html
- src/main/resources/static/docs/scrap.html
- src/main/resources/static/docs/user.html
- src/test/kotlin/com/example/jhouse_server/domain/house/controller/HouseControllerTest.kt
- src/test/kotlin/com/example/jhouse_server/global/util/MockEntity.kt
> 한 줄로 정리해주세요.
빈집 게시글 상세조회 시, 유저 타입 데이터 추가
> [hotfix/house service] 빈집 게시글 상세조회 시, 유저 타입 데이터 추가

- build.gradle.kts
- src/main/kotlin/com/example/jhouse_server/domain/house/controller/HouseController.kt
- src/main/kotlin/com/example/jhouse_server/domain/house/dto/HouseReqDto.kt
- src/main/kotlin/com/example/jhouse_server/domain/house/entity/House.kt
- src/main/kotlin/com/example/jhouse_server/domain/house/repository/HouseRepositoryImpl.kt
- src/main/kotlin/com/example/jhouse_server/domain/house/service/HouseServiceImpl.kt
- src/main/kotlin/com/example/jhouse_server/global/config/RedisCacheConfig.kt
- src/main/resources/ehcache.xml
- src/main/resources/static/docs/board.html
- src/main/resources/static/docs/comment.html
- src/main/resources/static/docs/house.html
- src/main/resources/static/docs/love.html
- src/main/resources/static/docs/record.html
- src/main/resources/static/docs/record_category.html
- src/main/resources/static/docs/record_comment.html
- src/main/resources/static/docs/record_review.html
- src/main/resources/static/docs/scrap.html
- src/main/resources/static/docs/user.html
- src/test/kotlin/com/example/jhouse_server/domain/house/controller/HouseControllerTest.kt
- src/test/kotlin/com/example/jhouse_server/domain/house/service/HouseServiceImplTest.kt
> 한 줄로 정리해주세요.
Ehcache를 이용한 2차 캐싱 적용하였습니다.
- RedisCacheConfig에서 RedisCacheManager를 우선 사용하도록 설정
이유 : EhCacheManager와 동시에 cacheManager로 빈 등록 되면서 이슈가 발생하였고, 이를 해결하기 위해 Redis에 우선권을 부여하였습니다.
EhCacheManager를 사용하고자 할 때에는, 캐시 객체를 새로 생성해서 옵션을 커스터마이징 해야 하며 사용 시 @Cachable에서 manager를 지정해야 합니다.
> [Feat/house service] Ehcache를 이용한 2차 캐싱 적용

- src/main/kotlin/com/example/jhouse_server/domain/house/dto/HouseReqDto.kt
- src/main/kotlin/com/example/jhouse_server/domain/house/entity/House.kt
- src/main/kotlin/com/example/jhouse_server/domain/house/entity/ReportType.kt
- src/main/kotlin/com/example/jhouse_server/domain/house/service/HouseServiceImpl.kt
- src/main/resources/static/docs/board.html
- src/main/resources/static/docs/comment.html
- src/main/resources/static/docs/house.html
- src/main/resources/static/docs/love.html
- src/main/resources/static/docs/record.html
- src/main/resources/static/docs/record_category.html
- src/main/resources/static/docs/record_comment.html
- src/main/resources/static/docs/record_review.html
- src/main/resources/static/docs/scrap.html
- src/main/resources/static/docs/user.html
- src/test/kotlin/com/example/jhouse_server/domain/house/controller/HouseControllerTest.kt
- src/test/kotlin/com/example/jhouse_server/global/util/MockEntity.kt
> 한 줄로 정리해주세요.
신고하기 API 수정 -> 신고분류 컬럼 추가
> [Feat/house service] 신고하기 API 수정 -> 신고분류 컬럼 추가

- README.md
- src/docs/asciidoc/user.adoc
- src/main/kotlin/com/example/jhouse_server/domain/user/controller/UserController.kt
- src/main/kotlin/com/example/jhouse_server/domain/user/dto/UserDto.kt
- src/main/kotlin/com/example/jhouse_server/domain/user/entity/User.kt
- src/main/kotlin/com/example/jhouse_server/domain/user/entity/Withdrawal.kt
- src/main/kotlin/com/example/jhouse_server/domain/user/entity/WithdrawalReason.kt
- src/main/kotlin/com/example/jhouse_server/domain/user/entity/agent/Agent.kt
- src/main/kotlin/com/example/jhouse_server/domain/user/repository/WithdrawalRepository.kt
- src/main/kotlin/com/example/jhouse_server/domain/user/service/UserService.kt
- src/main/kotlin/com/example/jhouse_server/domain/user/service/UserServiceImpl.kt
- src/main/kotlin/com/example/jhouse_server/domain/user/service/agent/AgentServiceImpl.kt
- src/main/kotlin/com/example/jhouse_server/domain/user/service/common/UserServiceCommonMethod.kt
- src/main/kotlin/com/example/jhouse_server/global/exception/ErrorCode.kt
- src/main/resources/static/docs/board.html
- src/main/resources/static/docs/comment.html
- src/main/resources/static/docs/error.html
- src/main/resources/static/docs/house.html
- src/main/resources/static/docs/jwt.html
- src/main/resources/static/docs/love.html
- src/main/resources/static/docs/record.html
- src/main/resources/static/docs/record_category.html
- src/main/resources/static/docs/record_comment.html
- src/main/resources/static/docs/record_review.html
- src/main/resources/static/docs/scrap.html
- src/main/resources/static/docs/user.html
- src/test/kotlin/com/example/jhouse_server/domain/admin/user/AdminUserServiceTest.kt
- src/test/kotlin/com/example/jhouse_server/domain/user/controller/UserControllerTest.kt
- src/test/kotlin/com/example/jhouse_server/domain/user/service/UserServiceImplTest.kt
- src/test/kotlin/com/example/jhouse_server/global/util/MockEntity.kt
> [feat/user] 마이페이지 개발

- src/main/kotlin/com/example/jhouse_server/domain/board/repository/BoardRepositoryImpl.kt
- src/main/resources/static/docs/board.html
- src/main/resources/static/docs/comment.html
- src/main/resources/static/docs/house.html
- src/main/resources/static/docs/love.html
- src/main/resources/static/docs/notification.html
- src/main/resources/static/docs/record.html
- src/main/resources/static/docs/record_category.html
- src/main/resources/static/docs/record_comment.html
- src/main/resources/static/docs/record_review.html
- src/main/resources/static/docs/scrap.html
- src/main/resources/static/docs/user.html
> 한 줄로 정리해주세요.
커뮤니티 게시글 목록 조회 시, 댓글 갯수 오류 수정
> [hotfix] 커뮤니티 게시글 목록 조회 시, 댓글 갯수 오류 수정

- src/docs/asciidoc/user.adoc
- src/main/kotlin/com/example/jhouse_server/domain/user/dto/UserDto.kt
- src/main/resources/static/docs/board.html
- src/main/resources/static/docs/comment.html
- src/main/resources/static/docs/house.html
- src/main/resources/static/docs/love.html
- src/main/resources/static/docs/notification.html
- src/main/resources/static/docs/record.html
- src/main/resources/static/docs/record_category.html
- src/main/resources/static/docs/record_comment.html
- src/main/resources/static/docs/record_review.html
- src/main/resources/static/docs/scrap.html
- src/main/resources/static/docs/user.html
- src/test/kotlin/com/example/jhouse_server/domain/user/controller/UserControllerTest.kt
> [Hotfix/user service] 사용자 조회 API 응답 수정

- src/docs/asciidoc/house.adoc
- src/main/kotlin/com/example/jhouse_server/domain/house/dto/HouseReqDto.kt
- src/main/kotlin/com/example/jhouse_server/domain/house/repository/HouseRepositoryImpl.kt
- src/main/resources/static/docs/board.html
- src/main/resources/static/docs/comment.html
- src/main/resources/static/docs/house.html
- src/main/resources/static/docs/love.html
- src/main/resources/static/docs/notification.html
- src/main/resources/static/docs/record.html
- src/main/resources/static/docs/record_category.html
- src/main/resources/static/docs/record_comment.html
- src/main/resources/static/docs/record_review.html
- src/main/resources/static/docs/scrap.html
- src/main/resources/static/docs/user.html
- src/test/kotlin/com/example/jhouse_server/domain/house/controller/HouseControllerTest.kt
- src/test/kotlin/com/example/jhouse_server/domain/house/service/HouseServiceImplTest.kt
> 한 줄로 정리해주세요.
빈집 게시글 검색 조건 수정
> [Hotfix/house service] 빈집 게시글 검색 조건 수정

- src/main/kotlin/com/example/jhouse_server/domain/house/dto/HouseReqDto.kt
- src/main/kotlin/com/example/jhouse_server/domain/house/repository/HouseRepositoryImpl.kt
> 한 줄로 정리해주세요.
추천태그 필터링 DTO 타입 수정
> [fix] 추천태그 필터링 DTO 타입 수정

- src/main/kotlin/com/example/jhouse_server/domain/house/repository/HouseRepositoryImpl.kt
> 한 줄로 정리해주세요.
페이지네이션 countQuery 변경
countQuery에서 house 를 기준으로 조회된 데이터의 개수를 반환하는 것으로 변경
> [hotfix] 페이지네이션 countQuery 변경

- src/docs/asciidoc/user.adoc
- src/main/kotlin/com/example/jhouse_server/domain/user/dto/UserDto.kt
- src/main/kotlin/com/example/jhouse_server/domain/user/entity/Term.kt
- src/main/kotlin/com/example/jhouse_server/domain/user/entity/User.kt
- src/main/kotlin/com/example/jhouse_server/domain/user/entity/UserTerm.kt
- src/main/kotlin/com/example/jhouse_server/domain/user/repository/UserTermRepository.kt
- src/main/kotlin/com/example/jhouse_server/domain/user/service/UserServiceImpl.kt
- src/main/kotlin/com/example/jhouse_server/domain/user/service/common/UserServiceCommonMethod.kt
- src/main/kotlin/com/example/jhouse_server/global/exception/ErrorCode.kt
- src/main/resources/static/docs/board.html
- src/main/resources/static/docs/comment.html
- src/main/resources/static/docs/error.html
- src/main/resources/static/docs/house.html
- src/main/resources/static/docs/love.html
- src/main/resources/static/docs/notification.html
- src/main/resources/static/docs/record.html
- src/main/resources/static/docs/record_category.html
- src/main/resources/static/docs/record_comment.html
- src/main/resources/static/docs/record_review.html
- src/main/resources/static/docs/scrap.html
- src/main/resources/static/docs/user.html
- src/test/kotlin/com/example/jhouse_server/domain/user/controller/UserControllerTest.kt
- src/test/kotlin/com/example/jhouse_server/global/util/MockEntity.kt
> 한 줄로 정리해주세요.
회원가입 시, 약관 동의 내역 테이블 생성 및 로직 수정
> [feat] 회원가입 시, 약관 동의 내역 테이블 생성 및 로직 수정

- src/main/kotlin/com/example/jhouse_server/admin/house/controller/AdminHouseController.kt
- src/main/kotlin/com/example/jhouse_server/admin/house/dto/HouseSearch.kt
- src/main/kotlin/com/example/jhouse_server/admin/house/service/AdminHouseService.kt
- src/main/kotlin/com/example/jhouse_server/domain/house/controller/HouseController.kt
- src/main/kotlin/com/example/jhouse_server/domain/house/entity/Deal.kt
- src/main/kotlin/com/example/jhouse_server/domain/house/repository/DealRepository.kt
- src/main/kotlin/com/example/jhouse_server/domain/house/repository/DealRepositoryCustom.kt
- src/main/kotlin/com/example/jhouse_server/domain/house/repository/DealRepositoryImpl.kt
- src/main/kotlin/com/example/jhouse_server/domain/house/service/HouseServiceImpl.kt
- src/main/resources/templates/house/houseReview.html
- src/main/resources/templates/house/houses.html
- src/test/kotlin/com/example/jhouse_server/domain/house/service/HouseServiceImplTest.kt
> 한 줄로 정리해주세요.
관리자페이지 - 빈집 거래 후기 조회 페이지 개발
TO-DO : 만족도 점수, 구매자 연령대로 동적 필터링 가능하도록 수정
> [Feat/admin] 관리자페이지 - 빈집 거래 후기 조회 페이지 개발 (ODR-10)

- .github/release-drafter-config.yml
- .github/workflows/release-drafter.yml
> main <- dev

- src/main/kotlin/com/example/jhouse_server/admin/anaylsis/controller/AdminAnalysisController.kt
- src/main/kotlin/com/example/jhouse_server/admin/anaylsis/dto/AnalysisJoinPathResponse.kt
- src/main/kotlin/com/example/jhouse_server/admin/anaylsis/service/AnalysisService.kt
- src/main/kotlin/com/example/jhouse_server/domain/user/repository/UserRepositoryCustom.kt
- src/main/kotlin/com/example/jhouse_server/domain/user/repository/UserRepositoryImpl.kt
- src/main/resources/templates/analysis/age.html
- src/main/resources/templates/analysis/joinPath.html
- 가입연령, 가입경로 비율 외에 실제 경우의 수 값도 함께 노출되도록 수정
> [fix] 관리자페이지 데이터 시각화 수정 (ODR-17)

- src/main/kotlin/com/example/jhouse_server/admin/house/controller/AdminHouseController.kt
- src/main/kotlin/com/example/jhouse_server/admin/house/dto/HouseSearch.kt
- src/main/kotlin/com/example/jhouse_server/domain/house/repository/DealRepositoryImpl.kt
- src/main/resources/templates/house/houseReview.html
- src/main/resources/templates/house/houses.html
- 게시글 작성자 키워드 검색, 연령대 필터링, 점수 필터링 구현
> fix: 관리자페이지 거래 후기 필터링 구현 (ODR-19)

- .gitignore
- src/docs/asciidoc/house.adoc
- src/docs/asciidoc/index.adoc
- src/main/kotlin/com/example/jhouse_server/domain/house/controller/HouseController.kt
- src/main/kotlin/com/example/jhouse_server/domain/house/dto/HouseReqDto.kt
- src/main/kotlin/com/example/jhouse_server/domain/house/entity/DealStateConverter.kt
- src/main/kotlin/com/example/jhouse_server/domain/house/entity/House.kt
- src/main/kotlin/com/example/jhouse_server/domain/house/repository/HouseRepositoryCustom.kt
- src/main/kotlin/com/example/jhouse_server/domain/house/repository/HouseRepositoryImpl.kt
- src/main/kotlin/com/example/jhouse_server/domain/house/service/HouseService.kt
- src/main/kotlin/com/example/jhouse_server/domain/house/service/HouseServiceImpl.kt
- src/main/resources/static/docs/board.html
- src/main/resources/static/docs/comment.html
- src/main/resources/static/docs/house.html
- src/main/resources/static/docs/love.html
- src/main/resources/static/docs/notification.html
- src/main/resources/static/docs/record.html
- src/main/resources/static/docs/record_category.html
- src/main/resources/static/docs/record_comment.html
- src/main/resources/static/docs/record_review.html
- src/main/resources/static/docs/scrap.html
- src/main/resources/static/docs/user.html
- src/test/kotlin/com/example/jhouse_server/domain/house/controller/HouseControllerTest.kt
- src/test/kotlin/com/example/jhouse_server/domain/house/service/HouseServiceImplTest.kt
마이페이지 - 자신이 작성한 빈집 게시글 목록 조회
- 공인중개사 게시글 목록 조회 API 수정
- 일반유저/공인중개사 게시글 목록 조회 API 개발
- 빈집 게시글과 거래 양방향 one-to-one 관계 형성
이유 : join 시, 관계 참조를 위해
> [Feature/mypage] 마이페이지 - 자신이 작성한 빈집 게시글 목록 조회 (ODR-20)

- src/main/kotlin/com/example/jhouse_server/domain/house/service/HouseServiceImpl.kt
- src/main/kotlin/com/example/jhouse_server/global/exception/ErrorCode.kt
- src/test/kotlin/com/example/jhouse_server/domain/house/controller/HouseControllerTest.kt
- src/test/kotlin/com/example/jhouse_server/domain/house/service/HouseServiceImplTest.kt
빈집 게시글 판매 상태 변경 검증 로직 수정 (#269 )
> [Fix/update deal] 빈집 게시글 판매 상태 변경 검증 로직 수정

- .github/workflows/CD-dev.yml
> chore: 서버 인바운드 포트 변경

- src/main/kotlin/com/example/jhouse_server/domain/house/controller/HouseController.kt
- src/main/kotlin/com/example/jhouse_server/domain/house/repository/HouseRepositoryCustom.kt
- src/main/kotlin/com/example/jhouse_server/domain/house/repository/HouseRepositoryImpl.kt
- src/main/kotlin/com/example/jhouse_server/domain/house/service/HouseService.kt
- src/main/kotlin/com/example/jhouse_server/domain/house/service/HouseServiceImpl.kt
- src/main/resources/static/docs/board.html
- src/main/resources/static/docs/comment.html
- src/main/resources/static/docs/house.html
- src/main/resources/static/docs/love.html
- src/main/resources/static/docs/notification.html
- src/main/resources/static/docs/record.html
- src/main/resources/static/docs/record_category.html
- src/main/resources/static/docs/record_comment.html
- src/main/resources/static/docs/record_review.html
- src/main/resources/static/docs/scrap.html
- src/main/resources/static/docs/user.html
- src/test/kotlin/com/example/jhouse_server/domain/house/controller/HouseControllerTest.kt
빈집 게시글 스크랩 목록 조회 API 필터 추가
- 빈집 게시글 스크랩 목록 조회 API 필터 추가
- 마이페이지 빈집 게시글 조회 집계 쿼리에서 검색 조건절 제거
> [Hotfix/house service] 빈집 게시글 스크랩 목록 조회 API 필터 추가

- src/main/kotlin/com/example/jhouse_server/domain/board/dto/BoardReqDto.kt
- src/main/kotlin/com/example/jhouse_server/domain/board/dto/BoardResDto.kt
- src/main/kotlin/com/example/jhouse_server/domain/board/repository/BoardRepositoryCustom.kt
- src/main/kotlin/com/example/jhouse_server/domain/board/repository/BoardRepositoryImpl.kt
- src/main/kotlin/com/example/jhouse_server/domain/board/service/BoardServiceImpl.kt
커뮤니티 페이징 조회 쿼리 튜닝
- select 쿼리 4개 -> 1개로 축소
> fix: #305 커뮤니티 페이징 조회 쿼리 튜닝

- .github/workflows/CD-dev.yml
> Deploy for DEV

- .github/workflows/CD-dev.yml
> chore: cd 플로우 수정

- src/main/kotlin/com/example/jhouse_server/domain/house/repository/HouseRepositoryImpl.kt
> fix: #305 쿼리튜닝

- src/docs/asciidoc/user.adoc
- src/main/kotlin/com/example/jhouse_server/domain/user/controller/UserController.kt
- src/main/kotlin/com/example/jhouse_server/domain/user/entity/User.kt
- src/main/kotlin/com/example/jhouse_server/domain/user/service/UserService.kt
- src/main/kotlin/com/example/jhouse_server/domain/user/service/UserServiceImpl.kt
- src/main/resources/static/docs/board.html
- src/main/resources/static/docs/comment.html
- src/main/resources/static/docs/house.html
- src/main/resources/static/docs/love.html
- src/main/resources/static/docs/notification.html
- src/main/resources/static/docs/record.html
- src/main/resources/static/docs/record_category.html
- src/main/resources/static/docs/record_comment.html
- src/main/resources/static/docs/record_review.html
- src/main/resources/static/docs/scrap.html
- src/main/resources/static/docs/user.html
- src/test/kotlin/com/example/jhouse_server/domain/user/controller/UserControllerTest.kt
#335 
- 이메일 수정
- 전화번호 수정
- 비밀번호 확인
API 개발 및 테스트코드 작성
> [Hotfix/qa] 마이페이지- 회원정보 수정 API 추가 개발
